import { canonicalPortraitModel } from './portraitConstructionModel'
import type { PortraitConstructionModel } from './portraitConstructionModel'
export type PortraitRigDimensions={headScale:number;cranialWidth:number;cranialHeight:number;faceWidth:number;faceHeight:number;jawWidth:number;jawHeight:number;jawAngle:number;chinWidth:number;chinProjection:number;eyeSpacing:number;eyeWidth:number;eyeHeight:number;eyeTilt:number;browHeight:number;browTilt:number;noseLength:number;noseWidth:number;noseProjection:number;noseAngle:number;mouthWidth:number;mouthHeight:number;mouthProjection:number;earWidth:number;earHeight:number;earPosition:number;neckWidth:number;neckAngle:number}
export type PortraitRigPose={yaw:number;pitch:number;roll:number}; export type PortraitRigGaze={horizontal:number;vertical:number;convergence:number}; export type PortraitRigExpression={mouthOpen:number;smile:number;browRaiseLeft:number;browRaiseRight:number;eyeOpennessLeft:number;eyeOpennessRight:number;squint:number;jawOpen:number}; export type PortraitRigCamera={scale:number;perspective:number}
export type PortraitRigView='front'|'three-quarter-left'|'three-quarter-right'|'profile-left'|'profile-right'
export type PortraitRigParameters={dimensions:PortraitRigDimensions;pose:PortraitRigPose;gaze:PortraitRigGaze;expression:PortraitRigExpression;camera:PortraitRigCamera}
export const defaultPortraitRigParameters:PortraitRigParameters={dimensions:{headScale:1,cranialWidth:1,cranialHeight:1,faceWidth:1,faceHeight:1,jawWidth:1,jawHeight:1,jawAngle:0,chinWidth:1,chinProjection:1,eyeSpacing:1,eyeWidth:1,eyeHeight:1,eyeTilt:0,browHeight:0,browTilt:0,noseLength:1,noseWidth:1,noseProjection:1,noseAngle:0,mouthWidth:1,mouthHeight:1,mouthProjection:1,earWidth:1,earHeight:1,earPosition:1,neckWidth:1,neckAngle:0},pose:{yaw:0,pitch:0,roll:0},gaze:{horizontal:0,vertical:0,convergence:0},expression:{mouthOpen:0,smile:0,browRaiseLeft:0,browRaiseRight:0,eyeOpennessLeft:1,eyeOpennessRight:1,squint:0,jawOpen:0},camera:{scale:1,perspective:.18}}
export const portraitRigViewPresets:Record<PortraitRigView,{id:PortraitRigView;label:string;description:string;yaw:number;pitch:number;roll:number;perspective:number}>={front:{id:'front',label:'Face',description:'Axe médian',yaw:0,pitch:0,roll:0,perspective:.18},'three-quarter-left':{id:'three-quarter-left',label:'3/4 G',description:'Rotation gauche',yaw:-32,pitch:0,roll:0,perspective:.58},'three-quarter-right':{id:'three-quarter-right',label:'3/4 D',description:'Rotation droite',yaw:32,pitch:0,roll:0,perspective:.58},'profile-left':{id:'profile-left',label:'Profil G',description:'Vue latérale',yaw:-82,pitch:0,roll:0,perspective:.78},'profile-right':{id:'profile-right',label:'Profil D',description:'Vue latérale',yaw:82,pitch:0,roll:0,perspective:.78}}
export const isPortraitRigView=(v:unknown):v is PortraitRigView=>typeof v==='string'&&v in portraitRigViewPresets
export function normalizePortraitRigParameters(v:unknown):PortraitRigParameters { const s=(v&&typeof v==='object'?v:{}) as Partial<PortraitRigParameters>; return {...defaultPortraitRigParameters,...s,dimensions:{...defaultPortraitRigParameters.dimensions,...s.dimensions},pose:{...defaultPortraitRigParameters.pose,...s.pose},gaze:{...defaultPortraitRigParameters.gaze,...s.gaze},expression:{...defaultPortraitRigParameters.expression,...s.expression},camera:{...defaultPortraitRigParameters.camera,...s.camera}} }
export function initializePortraitRigView(view:PortraitRigView,p=defaultPortraitRigParameters):PortraitRigParameters { const preset=portraitRigViewPresets[view]; return {...normalizePortraitRigParameters(p),pose:{yaw:preset.yaw,pitch:preset.pitch,roll:preset.roll},camera:{...p.camera,perspective:preset.perspective}} }
export function createPortraitRig(supplied:unknown=defaultPortraitRigParameters,model:PortraitConstructionModel=canonicalPortraitModel):PortraitConstructionModel { const p=normalizePortraitRigParameters(supplied); const yaw=p.pose.yaw/88*.08; const scale=p.dimensions.headScale; return {...model,guides:model.guides.map(g=>{ const transform=(pt:{x:number;y:number;z:number})=>({x:.5+(pt.x-.5)*scale+yaw,y:pt.y,z:pt.z}); const geo=g.geometry.kind==='line'?{...g.geometry,from:transform(g.geometry.from),to:transform(g.geometry.to)}:g.geometry.kind==='polyline'?{...g.geometry,points:g.geometry.points.map(transform)}:g.geometry; return {...g,geometry:geo} })} }