import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import type { ChangeEvent, CSSProperties, DragEvent } from 'react'
import { Download, FileImage, FolderPlus, HelpCircle, ImagePlus, LockKeyhole, Minus, MoreHorizontal, Move, Plus, RotateCcw, ScanLine, Trash2, Upload } from 'lucide-react'
import { createPortraitRig, defaultPortraitRigParameters, initializePortraitRigView, portraitRigViewPresets } from './domain/portraitRig'
import type { PortraitRigDimensions, PortraitRigPose, PortraitRigView } from './domain/portraitRig'
import { derivePortraitConstructionModel, portraitConstructionMethods } from './domain/derivedPortraitModels'
import type { PortraitConstructionMethod } from './domain/derivedPortraitModels'
import { getRelevantPortraitRigGuides, projectPortraitRig } from './domain/portraitRigProjection'
import { parseProjectBackup, serializeProjectBackup } from './domain/projectBackup'
import { createVisionProvider } from './services/visionProvider'
import { useProjectStore } from './stores/projectStore'
import type { GuideLevel, ProjectDocument } from './types/project'
import type { VisionLandmark } from './types/vision'
import './App.css'

const levelLabels:Record<GuideLevel,string>={essential:'Essentiel',construction:'Construction',detailed:'Détaillé',expert:'Expert'}
const levels:GuideLevel[]=['essential','construction','detailed','expert']
const maxLevel:Record<GuideLevel,number>={essential:1,construction:2,detailed:3,expert:4}
const guideColors:Record<string,string>={cranium:'#d86b54',structure:'#d86b54',axes:'#607f9d',proportions:'#e5a048',eyes:'#607f9d',eyebrows:'#607f9d',nose:'#607f9d',mouth:'#607f9d',jaw:'#d86b54',ears:'#607f9d',neck:'#d86b54'}

function App(){
  const canvasRef=useRef<HTMLCanvasElement>(null)
  const frameRef=useRef<HTMLDivElement>(null)
  const imageRef=useRef<HTMLImageElement|null>(null)
  const backupInputRef=useRef<HTMLInputElement>(null)
  const {project,setProject,isReady,projectList,activeProjectId,switchProject,createProject,duplicateProject,importProject,deleteProject}=useProjectStore()
  const [dragging,setDragging]=useState(false)
  const [status,setStatus]=useState('Importez une image pour commencer')
  const [exportOpen,setExportOpen]=useState(false)
  const [manipulate,setManipulate]=useState(false)
  const [loadingImage,setLoadingImage]=useState(false)
  const [analyzing,setAnalyzing]=useState(false)
  const [visionResult,setVisionResult]=useState<{imageUrl:string;landmarks:VisionLandmark[]}|null>(null)
  const [guideOffset,setGuideOffset]=useState({x:0,y:0})
  const guideOffsetRef=useRef({x:0,y:0})
  const imageUrl=project.imageDataUrl||''
  const updateProject=useCallback((patch:Partial<ProjectDocument>)=>setProject(current=>({...current,...patch,updatedAt:Date.now()})),[setProject])
  const rig=useMemo(()=>createPortraitRig(project.rigParameters),[project.rigParameters])
  const construction=useMemo(()=>derivePortraitConstructionModel(rig,project.constructionMethod),[rig,project.constructionMethod])

  const draw=useCallback(()=>{
    const canvas=canvasRef.current;const frame=frameRef.current;const image=imageRef.current
    if(!canvas||!frame)return
    const width=frame.clientWidth;const height=frame.clientHeight;const ratio=window.devicePixelRatio||1
    canvas.width=width*ratio;canvas.height=height*ratio
    const ctx=canvas.getContext('2d');if(!ctx)return
    ctx.setTransform(ratio,0,0,ratio,0,0);ctx.clearRect(0,0,width,height);ctx.fillStyle='#e6e1d8';ctx.fillRect(0,0,width,height)
    if(!image)return
    const scale=Math.min(width/image.naturalWidth,height/image.naturalHeight)*project.zoom
    const imageWidth=image.naturalWidth*scale;const imageHeight=image.naturalHeight*scale;const x=(width-imageWidth)/2;const y=(height-imageHeight)/2
    ctx.save();ctx.translate(x,y);ctx.drawImage(image,0,0,imageWidth,imageHeight)
    ctx.globalAlpha=project.opacity/100
    if(project.gridVisible){ctx.strokeStyle='#f8f4e9';ctx.lineWidth=1;for(let i=1;i<4;i++){ctx.beginPath();ctx.moveTo(imageWidth*i/4,0);ctx.lineTo(imageWidth*i/4,imageHeight);ctx.stroke()}for(let i=1;i<5;i++){ctx.beginPath();ctx.moveTo(0,imageHeight*i/5);ctx.lineTo(imageWidth,imageHeight*i/5);ctx.stroke()}}
     if(project.guidesVisible){const guides=getRelevantPortraitRigGuides(projectPortraitRig(construction,{headOffsetX:project.guideAdjustments.headOffsetX+guideOffset.x,headOffsetY:project.guideAdjustments.headOffsetY+guideOffset.y,guideScale:project.guideAdjustments.scale}),project.rigParameters.pose.yaw);guides.forEach(g=>{if(!g.visibility||g.priority>maxLevel[project.level])return;const geo=g.geometry;ctx.strokeStyle=guideColors[g.category]||'#d86b54';ctx.fillStyle=ctx.strokeStyle;ctx.lineWidth=g.style==='volume'?1.8:1.15;ctx.setLineDash(g.style==='volume'?[7,5]:[]);ctx.beginPath();if(geo.kind==='point'){ctx.arc(geo.position.x*imageWidth,geo.position.y*imageHeight,3,0,Math.PI*2);ctx.fill()}else{const points=geo.kind==='line'?[geo.from,geo.to]:geo.points;points.forEach((p,i)=>i?ctx.lineTo(p.x*imageWidth,p.y*imageHeight):ctx.moveTo(p.x*imageWidth,p.y*imageHeight));if(geo.kind==='polyline'&&geo.closed)ctx.closePath();ctx.stroke()}ctx.setLineDash([])})}
     if(project.visionEnabled&&visionResult?.imageUrl===imageUrl&&visionResult.landmarks.length>0){ctx.save();ctx.globalAlpha=.55;ctx.fillStyle='#5f8ea8';visionResult.landmarks.forEach(point=>{ctx.beginPath();ctx.arc(point.x*imageWidth,point.y*imageHeight,2.5,0,Math.PI*2);ctx.fill()});ctx.restore()}
    ctx.restore()
   },[construction,guideOffset,imageUrl,project.guidesVisible,project.gridVisible,project.guideAdjustments,project.level,project.opacity,project.rigParameters.pose.yaw,project.visionEnabled,project.zoom,visionResult])

  useEffect(()=>{if(!imageUrl){imageRef.current=null;draw();return}setLoadingImage(true);const img=new Image();img.onload=()=>{imageRef.current=img;setLoadingImage(false);draw()};img.onerror=()=>{setLoadingImage(false);setStatus('Impossible de décoder cette image dans le navigateur.');imageRef.current=null};img.src=imageUrl;return()=>{img.onload=null;img.onerror=null}},[draw,imageUrl])
  useEffect(()=>{draw();const observer=new ResizeObserver(draw);if(frameRef.current)observer.observe(frameRef.current);return()=>observer.disconnect()},[draw,isReady])
  useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(e.target instanceof HTMLInputElement)return;if(e.key.toLowerCase()==='g')updateProject({gridVisible:!project.gridVisible});if(e.key.toLowerCase()==='h')updateProject({guidesVisible:!project.guidesVisible});if(e.key==='+')updateProject({zoom:Math.min(2,Number((project.zoom+.1).toFixed(2)))});if(e.key==='-')updateProject({zoom:Math.max(.5,Number((project.zoom-.1).toFixed(2)))})};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[project.gridVisible,project.guidesVisible,project.zoom,updateProject])

  const loadFile=async(file?:File)=>{if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){setStatus('Format non pris en charge. Utilisez JPG, PNG ou WebP.');return}if(file.size>20*1024*1024){setStatus('Image trop volumineuse. La limite est de 20 Mo.');return}setLoadingImage(true);setStatus('Chargement de la référence…');const reader=new FileReader();reader.onload=()=>{if(typeof reader.result==='string'){updateProject({imageDataUrl:reader.result,fileName:file.name});setStatus('Référence importée · vous pouvez ajuster les repères')}};reader.onerror=()=>{setLoadingImage(false);setStatus('La lecture locale a échoué. Réessayez.');};reader.readAsDataURL(file)}
  const analyzeReference=async()=>{if(!imageUrl||analyzing)return;setAnalyzing(true);setStatus('Analyse locale en cours · premier chargement du modèle…');try{const result=await createVisionProvider('mediapipe').analyze(imageUrl);if(result.suggestion){setVisionResult({imageUrl,landmarks:result.suggestion.landmarks});updateProject({visionEnabled:true,visionProvider:'mediapipe',showComparison:true});setStatus(`${result.suggestion.label} · vérifiez puis ajustez les repères`)}else{setStatus(result.error||'Aucun repère fiable détecté · corrigez le guide manuellement')}}finally{setAnalyzing(false)}}
  const onInput=(e:ChangeEvent<HTMLInputElement>)=>void loadFile(e.target.files?.[0])
  const onDrop=(e:DragEvent<HTMLDivElement>)=>{e.preventDefault();setDragging(false);void loadFile(e.dataTransfer.files?.[0])}
  const exportPng=()=>{if(!imageUrl||!canvasRef.current)return;setStatus('Guide exporté en PNG');const link=document.createElement('a');link.download=`${(project.fileName||'portrait-facile').replace(/\.[^/.]+$/,'')}-guide.png`;link.href=canvasRef.current.toDataURL('image/png');link.click();setExportOpen(false)}
  const updateDim=(key:keyof PortraitRigDimensions,value:number)=>updateProject({rigParameters:{...project.rigParameters,dimensions:{...project.rigParameters.dimensions,[key]:value}}})
  const updatePose=(key:keyof PortraitRigPose,value:number)=>updateProject({rigParameters:{...project.rigParameters,pose:{...project.rigParameters.pose,[key]:value}}})
  const setView=(view:PortraitRigView)=>{updateProject({rigView:view,rigParameters:initializePortraitRigView(view,project.rigParameters)});setStatus(`Vue ${portraitRigViewPresets[view].label} sélectionnée`)}
  const backup=()=>{const blob=new Blob([serializeProjectBackup(project)],{type:'application/json'});const link=document.createElement('a');link.download=`${project.fileName||'portrait-facile'}.json`;link.href=URL.createObjectURL(blob);link.click();URL.revokeObjectURL(link.href)}
  const restore=(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=async()=>{try{await importProject(parseProjectBackup(String(reader.result)));setStatus('Projet restauré depuis la sauvegarde')}catch{setStatus('Sauvegarde invalide ou non reconnue')}};reader.readAsText(file)}
  const hasImage=Boolean(imageUrl)
  const workflowStep=!hasImage?1:project.constructionMethod!=='canonical'||project.rigView!=='front'||project.guideAdjustments.scale!==1?3:2
  const visibleProjectName=project.fileName||'Sans référence'

  if(!isReady)return <div className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark">↗</span><span>portrait <em>facile</em></span></div><div className="skeleton" style={{width:140,height:10}}/></header><main style={{padding:35}}><div className="skeleton" style={{height:24,width:210,marginBottom:18}}/><div className="skeleton" style={{height:'70dvh',width:'100%'}}/></main></div>
  return <div className="app-shell">
    <header className="topbar">
      <a className="brand" href="/" data-testid="link-home"><span className="brand-mark">↗</span><span>portrait <em>facile</em></span></a>
      <div className="topbar-actions"><div className="project-summary"><span className="summary-label">Atelier local</span><strong data-testid="text-project-name">{visibleProjectName}</strong></div><div className="privacy-note"><span className="status-dot"/><span>Vos images restent sur cet appareil</span></div><div className="header-actions"><button className="header-button" data-testid="button-help" onClick={()=>setStatus('Astuce : G pour la grille · H pour les guides · + / − pour zoomer')}><HelpCircle size={13}/> Aide</button><button className="icon-button" aria-label="Plus d’options" data-testid="button-header-options" onClick={()=>setStatus('Les projets sont enregistrés automatiquement dans cet appareil.')}><MoreHorizontal size={15}/></button></div></div>
    </header>
    <div className="workspace">
      <aside className="sidebar">
        <div className="sidebar-heading"><div><div className="eyebrow">Atelier de construction</div><h1>Construire un portrait</h1></div><button className="more-button" aria-label="Créer un projet" data-testid="button-new-project" onClick={()=>void createProject('Nouveau projet')}><Plus size={18}/></button></div>
        <nav className="step-list" aria-label="Étapes de travail">
          {[['01','Référence','Importer une image'],['02','Construction','Poser les repères'],['03','Ajustements','Préparer le dessin']].map(([number,label,detail],index)=><div className={`step ${workflowStep===index+1?'active':''} ${workflowStep>index+1?'completed':''}`} key={number}><span>{workflowStep>index+1?'✓':number}</span><div><strong>{label}</strong><small>{detail}</small></div></div>)}
        </nav>
        <section className="panel-section project-list-panel"><div className="section-title"><span>Projets récents</span><span className="live-label">● local</span></div><div className="project-list">{projectList.length===0?<div className="empty-projects">Votre atelier est prêt.</div>:projectList.slice(0,4).map(item=><div className={`project-item ${item.id===activeProjectId?'selected':''}`} key={item.id}><button className="project-main" data-testid={`button-project-${item.id}`} onClick={()=>void switchProject(item.id)}><span className="project-name">{item.fileName||'Sans référence'}</span><span className="project-meta">{item.imageDataUrl?'Image importée':'Brouillon local'}</span></button><div className="project-actions"><button className="project-action" aria-label="Dupliquer le projet" data-testid={`button-duplicate-${item.id}`} onClick={()=>void duplicateProject(item)}><FileImage size={12}/></button><button className="project-delete" aria-label="Supprimer le projet" data-testid={`button-delete-${item.id}`} onClick={()=>void deleteProject(item.id)}><Trash2 size={12}/></button></div></div>)}</div><button className="text-button secondary-project-action" data-testid="button-create-project" onClick={()=>void createProject('Nouveau projet')}><FolderPlus size={13}/> Nouveau projet</button><div className="project-backup-actions"><button data-testid="button-backup-export" onClick={backup}>Sauvegarder</button><button data-testid="button-backup-import" onClick={()=>backupInputRef.current?.click()}>Restaurer</button><input ref={backupInputRef} className="backup-file-input" type="file" accept="application/json" onChange={restore}/><span className="project-backup-note">Projet et image conservés localement dans ce navigateur.</span></div></section>
        <section className="panel-section"><div className="section-title"><span>Affichage</span><strong>{project.opacity}%</strong></div><label className="control-row"><span><span className="swatch swatch-grid"/>Grille d’étude</span><input type="checkbox" checked={project.gridVisible} onChange={e=>updateProject({gridVisible:e.target.checked})} data-testid="toggle-grid"/></label><label className="control-row"><span><span className="swatch swatch-guide"/>Guides de construction</span><input type="checkbox" checked={project.guidesVisible} onChange={e=>updateProject({guidesVisible:e.target.checked})} data-testid="toggle-guides"/></label><div className="control-row"><span>Opacité du guide</span><strong>{project.opacity}%</strong></div><input className="range" type="range" min="20" max="100" value={project.opacity} style={{'--fill':`${project.opacity}%`} as CSSProperties} onChange={e=>updateProject({opacity:Number(e.target.value)})} data-testid="range-opacity"/></section>
        <section className="panel-section"><div className="section-title"><span>Niveau de repères</span><HelpCircle className="info" size={15}/></div><div className="level-picker">{levels.map(l=><button className={project.level===l?'selected':''} key={l} onClick={()=>updateProject({level:l})} data-testid={`button-level-${l}`}>{levelLabels[l]}</button>)}</div></section>
         <section className="panel-section fit-panel"><div className="section-title"><span>Modèle de construction</span><strong>RIG</strong></div><div className="method-picker">{(Object.keys(portraitConstructionMethods) as PortraitConstructionMethod[]).map(method=><button className={project.constructionMethod===method?'selected':''} key={method} onClick={()=>{updateProject({constructionMethod:method});setStatus(`Méthode ${portraitConstructionMethods[method].label} sélectionnée`)}} data-testid={`button-method-${method}`}>{portraitConstructionMethods[method].label}</button>)}</div><p className="helper-text">Un même rig paramétrique, quatre façons de le lire sur le papier.</p><button className="fit-action" disabled={!hasImage||analyzing} onClick={()=>void analyzeReference()} data-testid="button-fit-reference"><ScanLine size={13}/> {analyzing?'Analyse locale…':'Analyser la référence'}</button><span className="fit-note">MediaPipe travaille dans ce navigateur · aucune image n’est envoyée.</span></section>
        <section className="panel-section rig-panel"><div className="section-title"><span>Réglages de pose</span><strong>{project.rigParameters.pose.yaw}°</strong></div><div className="view-picker">{(Object.keys(portraitRigViewPresets) as PortraitRigView[]).map(view=><button className={project.rigView===view?'selected':''} key={view} onClick={()=>setView(view)} data-testid={`button-view-${view}`}>{portraitRigViewPresets[view].label}</button>)}</div><label className="compact-control"><span>Rotation horizontale <b>{project.rigParameters.pose.yaw}°</b></span><input className="range" type="range" min="-88" max="88" value={project.rigParameters.pose.yaw} style={{'--fill':`${((project.rigParameters.pose.yaw+88)/176)*100}%`} as CSSProperties} onChange={e=>updatePose('yaw',Number(e.target.value))} data-testid="range-yaw"/></label><details className="rig-advanced"><summary>Proportions avancées</summary><label className="compact-control"><span>Largeur du visage <b>{project.rigParameters.dimensions.faceWidth.toFixed(2)}</b></span><input className="range" type="range" min=".78" max="1.22" step=".01" value={project.rigParameters.dimensions.faceWidth} onChange={e=>updateDim('faceWidth',Number(e.target.value))} data-testid="range-face-width"/></label><label className="compact-control"><span>Hauteur du crâne <b>{project.rigParameters.dimensions.cranialHeight.toFixed(2)}</b></span><input className="range" type="range" min=".78" max="1.22" step=".01" value={project.rigParameters.dimensions.cranialHeight} onChange={e=>updateDim('cranialHeight',Number(e.target.value))} data-testid="range-cranium-height"/></label><button className="text-button reset-button" onClick={()=>updateProject({rigParameters:defaultPortraitRigParameters})} data-testid="button-reset-rig"><RotateCcw size={12}/> Réinitialiser le rig</button></details></section>
        <div className="sidebar-footer"><span className="version">PF · 01.0</span><button className="text-button" data-testid="button-privacy" onClick={()=>setStatus('Tout reste local : image, projet et export ne quittent pas cet appareil.')}>Confidentialité</button></div>
      </aside>
      <main className="canvas-area">
        <div className="canvas-toolbar"><div className="breadcrumb"><strong>{visibleProjectName}</strong><b>/</b><span>{construction.name}</span></div><div className="toolbar-actions"><button className="tool-button" aria-label="Zoom arrière" data-testid="button-zoom-out" onClick={()=>updateProject({zoom:Math.max(.5,Number((project.zoom-.1).toFixed(2)))})}><Minus size={15}/></button><span className="zoom-label" data-testid="text-zoom">{Math.round(project.zoom*100)}%</span><button className="tool-button" aria-label="Zoom avant" data-testid="button-zoom-in" onClick={()=>updateProject({zoom:Math.min(2,Number((project.zoom+.1).toFixed(2)))})}><Plus size={15}/></button><button className="fit-button" data-testid="button-zoom-fit" onClick={()=>updateProject({zoom:1})}>Ajuster</button><button className={`manipulate-button ${manipulate?'selected':''}`} disabled={!hasImage||!project.guidesVisible} onClick={()=>setManipulate(v=>!v)} data-testid="button-manipulate"><Move size={13}/> Déplacer les repères</button><div className="export-actions"><button className="export-button" disabled={!hasImage||loadingImage} onClick={exportPng} data-testid="button-export"><Download size={13}/> Exporter<span>PNG</span></button><button className="export-options-button" disabled={!hasImage} aria-label="Options d’export" onClick={()=>setExportOpen(v=>!v)} data-testid="button-export-options">⌄</button>{exportOpen&&<div className="export-menu-panel"><button onClick={exportPng} data-testid="button-export-png"><strong>Guide PNG</strong><span>Image de référence et repères superposés</span></button><button onClick={()=>{setExportOpen(false);setStatus('Export haute résolution disponible dans le guide PNG.')}} data-testid="button-export-info"><strong>Conseil papier</strong><span>Utilisez une opacité de 42 à 58% pour imprimer.</span></button></div>}</div></div></div>
        <div ref={frameRef} className={`canvas-frame ${dragging?'dragging':''}`} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={onDrop}>
          <canvas ref={canvasRef} data-testid="canvas-preview"/>
          {!hasImage&&!loadingImage&&<div className="drop-message"><div className="upload-icon"><ImagePlus size={22}/></div><h2>Une photo, puis le geste.</h2><p>Importez une référence pour poser les axes, le crâne, la mâchoire et les proportions avant de dessiner.</p><label className="upload-button" data-testid="button-upload"><Upload size={14}/> Choisir une image<input type="file" accept="image/jpeg,image/png,image/webp" onChange={onInput}/></label><span className="file-hint">JPG · PNG · WEBP · 20 MO MAX</span></div>}
          {loadingImage&&<div className="drop-message"><div className="skeleton" style={{width:110,height:12}}/><div className="skeleton" style={{width:180,height:9,marginTop:12}}/></div>}
          {manipulate&&hasImage&&<div className="guide-selection" style={{left:'27%',top:'12%',width:'46%',height:'76%'}}><button className="guide-move-target" aria-label="Déplacer les repères" onPointerDown={e=>{const start={x:e.clientX,y:e.clientY};const initial={...guideOffsetRef.current};const move=(ev:PointerEvent)=>{const next={x:initial.x+(ev.clientX-start.x)/((frameRef.current?.clientWidth||500)),y:initial.y+(ev.clientY-start.y)/((frameRef.current?.clientHeight||500))};guideOffsetRef.current=next;setGuideOffset(next)};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);const latest=guideOffsetRef.current;updateProject({guideAdjustments:{...project.guideAdjustments,headOffsetX:project.guideAdjustments.headOffsetX+latest.x,headOffsetY:project.guideAdjustments.headOffsetY+latest.y}});guideOffsetRef.current={x:0,y:0};setGuideOffset({x:0,y:0});setStatus('Repères repositionnés · ajustement enregistré')};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}}/><button className="guide-scale-handle" aria-label="Redimensionner les repères" onClick={()=>{updateProject({guideAdjustments:{...project.guideAdjustments,scale:Math.min(1.35,Number((project.guideAdjustments.scale+.05).toFixed(2)))}});setStatus('Taille des repères ajustée')}}/></div>}
        </div>
        <footer className="canvas-footer"><div className="status-message"><span className="status-dot"/><span data-testid="status-message">{status}</span></div><div className="shortcut-hint"><span>Raccourcis</span><kbd>G</kbd><kbd>H</kbd><kbd>+</kbd><kbd>−</kbd><LockKeyhole size={11}/></div></footer>
      </main>
    </div>
  </div>
}

export default App